FitnessForLife/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessForLife.Models;

namespace FitnessForLife.Controllers
{
    public class BranchesController : Controller
    {
        private FitnessForLifeModel db = new FitnessForLifeModel();

        // GET: Branches
        public ActionResult Index()
        {
            if (User.IsInRole("FitnessManager"))
                return View("IndexAdmin", db.Branches.ToList());
            return View("IndexUser", db.Branches.ToList());
        }

        // GET: Branches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // GET: Branches/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Branches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,Address")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Branches.Add(branch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        // GET: Branches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branches/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Address")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(branch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        // GET: Branches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        // POST: Branches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            foreach(var row in db.Appointments.Where(a => a.Branch == id).ToList())
            {
                db.Appointments.Remove(row);            
            }
            Branch branch = db.Branches.Find(id);
            db.Branches.Remove(branch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnessForLife/Controllers/ConsultantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessForLife.Models;

namespace FitnessForLife.Controllers
{
    public class ConsultantsController : Controller
    {
        private FitnessForLifeModel db = new FitnessForLifeModel();

        // GET: Consultants
        public ActionResult Index()
        {
            return View(db.Consultants.ToList());
        }

        // GET: Consultants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultant consultant = db.Consultants.Find(id);
            if (consultant == null)
            {
                return HttpNotFound();
            }
            return View(consultant);
        }

        // GET: Consultants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Consultants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Full_Name,Date_of_birth,Address,PhoneNumber,Email")] Consultant consultant)
        {
            if (ModelState.IsValid)
            {
                db.Consultants.Add(consultant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(consultant);
        }

        // GET: Consultants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultant consultant = db.Consultants.Find(id);
            if (consultant == null)
            {
                return HttpNotFound();
            }
            return View(consultant);
        }

        // POST: Consultants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Full_Name,Date_of_birth,Address,PhoneNumber,Email")] Consultant consultant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consultant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(consultant);
        }

        // GET: Consultants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultant consultant = db.Consultants.Find(id);
            if (consultant == null)
            {
                return HttpNotFound();
            }
            return View(consultant);
        }

        // POST: Consultants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consultant consultant = db.Consultants.Find(id);
            db.Consultants.Remove(consultant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnessForLife/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitnessForLife.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if(User.Identity.IsAuthenticated && !User.IsInRole("FitnessManager"))
                return View("IndexUser");
            if (User.IsInRole("FitnessManager"))
                return View("IndexAdmin");
            return View("Index");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Stay Healthy. Stay fit.";
  
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contact Us";

            return View();
        }

        public ActionResult Appointment()
        { 
            return View();
        }
    }
}

FitnessForLife/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessForLife.Models;
using Microsoft.AspNet.Identity;
using FitnessForLife.Utils;
using System.IO;

namespace FitnessForLife.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private FitnessForLifeModel db = new FitnessForLifeModel();

        // GET: Users
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user.Path == null)
            {
                user.Path = "defaultpic.jpg";
            }
            if (user == null)
            {
                return HttpNotFound();
            }
            if (User.IsInRole("FitnessManager"))
            {
                return View("DetailsAdmin", user);
            }
            return View("DetailsUser", user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,First_Name,Last_Name,Date_of_birth,Address,PhoneNumber,Path")] User user, HttpPostedFileBase postedFile)
        {
            ModelState.Clear();
            var myUniqueFileName = string.Format(@"{0}", Guid.NewGuid());
            user.Path = myUniqueFileName;
            TryValidateModel(user);

            if (ModelState.IsValid)
            {
                try
                {
                    string toEmail = User.Identity.GetUserName();
                    string subject = "Welcome to Fitness For Life";
                    string contents = "You have successfully registered with fitness for life. " +
                                        "Now you can access our facilities by booking appointment with our fitness consultant" +
                                        "<br><br>Let's begin our journey to fitness!!!";

                    EmailSender es = new EmailSender();
                    es.Send(toEmail, subject, contents);
                    ModelState.Clear();
                }
                catch
                {
                    return View();
                }

                string serverPath = Server.MapPath("~/Uploads/");
                string fileExtension = Path.GetExtension(postedFile.FileName);
                string filePath = user.Path + fileExtension;
                user.Path = filePath;
                postedFile.SaveAs(serverPath + user.Path);

                user.Id = User.Identity.GetUserId();
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,First_Name,Last_Name,Date_of_birth,Address,PhoneNumber,Path")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FitnessForLife/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2 class="start">@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FitnessForLife/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2 class="start">@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FitnessForLife/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

    <img src="~/Content/fitnessforlife.jpg" class="img-fluid start" alt="Responsive image" />

    <div class="row">
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Book an Appointment", "Index", "Appointments", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">Have a chat with our trainers and nutritionists. Get an estimate of your ideal weight and select from a wide-range of fiteness programs. Our experts will help you achieve your goals.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Our Branches", "Index", "Branches", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">We have 50+ centers in different cities all over Australia. Take a look at our locations and visit one near you.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header card-title text-white bg-secondary">Some Tips</h4>
                <div class="card-body">
                    <p class="card-text">Get some tips and tricks to follow in your daily life to burn some calories and keep yourself fit and active from our consultants.</p>
                </div>
            </div>
        </div>
    </div>

FitnessForLife/Views/Home/IndexAdmin.cshtml
@{
    ViewBag.Title = "Home";
}

    <img src="~/Content/fitnessforlife.jpg" class="img-fluid start" alt="Responsive image" />

    <div class="row">
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Create Appointments", "Index", "Appointments", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">As an owner of Fitness for Life you can create appointments for users so that they can view the available appointments.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Manage Branches", "Index", "Branches", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">As an owner of Fitness for Life you can create/edit/delete Fitness centers if you open a new center of close an old one.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Manage Appointments", "Manage", "Appointments", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">As an owner of Fitness for Life you can manage appointments for users so that they can view the available appointments.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Manage Consultants", "Index", "Consultants", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">As an owner of Fitness for Life you can manage consultants information in your centers.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-3" style="max-width: 20rem;">
                <h4 class="card-header bg-secondary">@Html.ActionLink("Manage Customers", "Index", "Users", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
                <div class="card-body">
                    <p class="card-text">Manage your customers here.</p>
                </div>
            </div>
        </div>
    </div>

FitnessForLife/Views/Home/IndexUser.cshtml
@using Microsoft.AspNet.Identity

@{
                /**/

                ViewBag.Title = "Home";
}
<img src="~/Content/fitnessforlife.jpg" class="img-fluid start" alt="Responsive image" />
<div class="row">
    <div class="col-md-4">
        <div class="card mb-3" style="max-width: 20rem;">
            <h4 class="card-header bg-secondary">@Html.ActionLink("Book an Appointment", "Index", "Appointments", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
            <div class="card-body">
                <p class="card-text">Have a chat with our trainers and nutritionists. Get an estimate of your ideal weight and select from a wide-range of fiteness programs. Our experts will help you achieve your goals.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-3" style="max-width: 20rem;">
            <h4 class="card-header bg-secondary">@Html.ActionLink("Our Branches", "Index", "Branches", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
            <div class="card-body">
                <p class="card-text">We have 50+ centers in different cities all over Australia. Take a look at our locations and visit one near you.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-3" style="max-width: 20rem;">
            <h4 class="card-header bg-secondary">@Html.ActionLink("Your Appointments", "Manage", "Appointments", routeValues: null, htmlAttributes: new { @class = "card-title text-white" })</h4>
            <div class="card-body">
                <p class="card-text">Manage your appointments here.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-3" style="max-width: 20rem;">
            <h4 class="card-header bg-secondary">@Html.ActionLink("My Details", "Details", "Users", new { id = User.Identity.GetUserId() }, htmlAttributes: new { @class = "card-title text-white" })</h4>
            <div class="card-body">
                <p class="card-text">Manage your appointments here.</p>
            </div>
        </div>
    </div>
</div>